services:
# # proxy
#   traefik:
#     image: traefik:v2.6
#     command:
#       - "--api.insecure=true"
#       - "--providers.docker"
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock"


  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=$4**jd!@kdLL
    ports:
      - 3307:3306
    networks:
      - obe
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9089:80
    depends_on:
      - mysql
    environment:
      # - MYSQL_ROOT_PASSWORD=$4**jd!@kdLL
      - PMA_HOST=mysql
      # - PMA_PORT=3307
    networks:
      - obe

  uczen:
    build: .
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=rekolekcje
      - DB_USERNAME=root
      - DB_PASSWORD=$4**jd!@kdLL
      - DB_PORT=3306
    ports:
      # 3000
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - obe
    labels:
      - traefik.enable=true
      - traefik.http.routers.uczen.rule=Host(`uczen.localhost`)

  admin_panel:
    build: 
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - ./admin/app:/var/www/html
    ports:
      - 8080:80
    networks:
      - obe
    depends_on:
      - mysql

networks:
  obe:
    name: obe
